### ISSUE TITLE
Unparsable file falls back to defaults

### ISSUE THREAD

**Issue by blast-hardcheese** [scalameta/sbt-scalafmt#12]
### Setup
addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "1.5.1")

### Description
Seems as though #7 has resurfaced; In a project that has a `.scalafmt.conf`, simply add a bare string to the top of the file, like so:

```
diff --git a/.scalafmt.conf b/.scalafmt.conf
index 26e120b9..be047b6a 100644
--- a/.scalafmt.conf
+++ b/.scalafmt.conf
@@ -1,14 +1,4 @@
+bogus
 
 style = defaultWithAlign
 ```

**Comment by tanishiking** [comment]
@blast-hardcheese As of sbt-scalafmt 2.0.0-RC5,  sbt-scalafmt will throw an exception immediately instead of falling back to defaults when `.scalafmt.conf` is unparsable (or invalid).
Could you upgrade sbt-scalafmt ?

Besides, sbt-scalafmt 2.0.0-RC5 has a feature that switches the running version of scalafmt using `version` in `.scalafmt.conf` (like `version = 1.5.1`).
