### ISSUE TITLE
Support Scalafmt 2

### ISSUE THREAD

**Issue by dwijnand** [scalameta/sbt-scalafmt#15]
Scalafmt 2 is currently in pre-release (https://github.com/scalameta/scalafmt/releases/tag/v2.0.0-RC4).

It would be nice to continue to have the same tight integration with sbt, but with the new version of Scalafmt.

**Comment by ches** [comment]
Wondering if we can compile a checklist here of what needs to be done—note @olafurpg's 
https://github.com/scalameta/sbt-scalafmt/pull/13#issuecomment-459348387 about the removal of scalafmt-big and introduction of [scalafmt-dynamic](https://github.com/scalameta/scalafmt/issues/1318) (which should allow sbt-scalafmt's release cycle to be decoupled from scalafmt versions going forward).

A nice one for release notes once unblocked: #13 added a `scalafmtIncremental` task that is now used for `scalafmtOnCompile` so that only files that need incremental compilation get formatted.

**Comment by tanishiking** [comment]
I'm working on progress on supporting sbt-scalafmt to use `scalafmt-dynamic` https://github.com/tanishiking/sbt-scalafmt/commit/863ff86e1a00a99cea10259834a07ba65f4115c4
In order to continue to support `scalafmtCli` command, it is necessary that https://github.com/scalameta/scalafmt/pull/1366 is released. FYI @olafurpg

**Comment by olafurpg** [comment]
@tanishiking Sounds good, you should be able to cut a new release at https://github.com/scalameta/scalafmt/releases/new the CI publishes artifacts on tag push. Note that the sbt plugin cannot depend on scalafmt-core directly, we'll need to use only scalafmt-dynamic

**Comment by tanishiking** [comment]
OK, I'll cut the new release (v2.0.0-RC5) :rocket:

**Comment by olafurpg** [comment]
Looks like it's already out!
```
coursier fetch org.scalameta:scalafmt-core_2.12:2.0.0-RC5
```
