### ISSUE TITLE
Plugin doesn't format a separate integration tests module

### ISSUE THREAD

**Issue by matejcerny** [scalameta/sbt-scalafmt#296]
After migrating IT to a separate module (due to [sbt 1.9.x](https://github.com/sbt/sbt/releases/tag/v1.9.0)), the plugin stopped formatting the code in that module.

#### before the change

```scala
lazy val core = project
  .in(file("core"))
  .configs(IntegrationTest)
  .settings(
    name := "core",
    Defaults.itSettings,
    ...
  )
```

#### after the change

```scala
lazy val core = project
  .in(file("core"))
  .settings(
    name := "core",
    ...
  )

lazy val IntegrationTest = (project in file("it"))
  .settings(
    publish / skip := true,
    ...
  )
  .dependsOn(core)
```

#### scalafmt version: 3.4.3

I also tried explicitly enabling `scalafmt := true` in the module's settings, but without any success.

Thanks for the help; it's likely just a misconfiguration.

**Comment by kitbellew** [comment]
is it different from #264?

**Comment by kitbellew** [comment]
@matejcerny thanks. at this point, since you're not actually sharing a reproducible example, there's not much anyone could do to fix this. also, there are examples when this works so it's not a universal problem.

**Comment by mzuehlke** [comment]
@matejcerny you haven't aggregated the `IntegrationTest` project in the `root` project. Probably because you don't want to execute the integration test when running `sbt test`. But this also means `scalafmtAll` is not automatically executed in that project.

You have 2 options:
* aggregate `IntegrationTest`  in the `root` project.
* invoke scalafmt explicitly: `sbt scalafmtAll IntegrationTest/scalafmtAll`

**Comment by matejcerny** [comment]
Thanks for the help @mzuehlke!
