### ISSUE TITLE
Cache behavior of scalafmtCheck wrt errors could be improved

### ISSUE THREAD

**Issue by jrudolph** [scalameta/sbt-scalafmt#42]
/cc @bjaglin

**Comment by jrudolph** [comment]
No, the problem was actually related to errors reported by `scalafmtCheck`. What happens is that the cache isn't stored when there's an error. What should happen instead is that the cache should be stored for all valid checks but not for the invalid ones, so that on rerun only the previous errors should be rechecked / re-reported.

**Comment by poslegm** [comment]
Yes, it is not regression in 2.0.3. Reproduces in 2.0.1.

It it what you want?

### Current behavior
```
[info] Checking 701 Scala sources...
[warn] /Users/poslegm/Documents/xxx/yyy/src/main/scala/kek.scala isn't formatted properly!
[error] 1 files must be formatted
[error] (core / Compile / scalafmtCheck) 1 files must be formatted
[error] Total time: 18 s, completed Aug 8, 2019, 6:46:00 PM
sbt:root> scalafmtCheck
[info] Checking 701 Scala sources...
```

### Expected behavior 
```
[info] Checking 701 Scala sources...
[warn] /Users/poslegm/Documents/xxx/yyy/src/main/scala/kek.scala isn't formatted properly!
[error] 1 files must be formatted
[error] (core / Compile / scalafmtCheck) 1 files must be formatted
[error] Total time: 18 s, completed Aug 8, 2019, 6:46:00 PM
sbt:root> scalafmtCheck
[info] Checking 1 Scala sources...
```

**Comment by bjaglin** [comment]
Indeed, `scalafmtCheck` is not incremental when at least one file was not formatted at the last run. 

Calling https://github.com/sbt/util/blob/7431dbd/util-tracking/src/main/scala/sbt/util/Tracked.scala#L301 again if the cached function fails (and return a subset of files) should allow us to update the cache with the validated sources only. I can take a look at that since the code is still fresh in my memory.

**Comment by jrudolph** [comment]
> I can take a look at that since the code is still fresh in my memory.

Thanks a lot!
