### ISSUE TITLE
Have scalafmt warn instead of error (or option)

### ISSUE THREAD

**Issue by pauljamescleary** [scalameta/sbt-scalafmt#75]
Is it possible to configure scalafmt to warn instead of error?  We have certain unavoidable `search state exploded` and would be great if we could skip that instead of `format off`

**Comment by poslegm** [comment]
Currently there is no configuration for it. Why don't you want to `// format: off` problem code?

**Comment by pauljamescleary** [comment]
@poslegm I am updating an in-house common custom plugin that is on an old version of scalafmt that only does **warn**.  That custom plugin pulls in scalafmt and is currently used by many projects.  if any project takes the update they would have to `// format: off` which makes it unlikely they would take the upgrade.


I would be happy to contribute if someone can point me in the right direction.

**Comment by poslegm** [comment]
Ok, I understand you.

I suppose that plugin ends with error because of `SearchStateExploded` exception on [formatSources](https://github.com/scalameta/sbt-scalafmt/blob/master/plugin/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala#L155) and [checkSources](https://github.com/scalameta/sbt-scalafmt/blob/master/plugin/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala#L221) calls. You can try to catch it and `log.warn` message instead of fail.

You can create [taskKey](https://github.com/scalameta/sbt-scalafmt/blob/master/plugin/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala#L52) to switch between fail and warn behavior.

**Comment by pauljamescleary** [comment]
@poslegm the "custom" plugin simply pulls in scalafmt but older in this case.  It isn't code, just a way to enforce standards.

**Comment by tanishiking** [comment]
@pauljamescleary Thank you for reporting!
Since `SearchStateExplodedException` comes from [here](https://github.com/scalameta/scalafmt/blob/d632143e838e829028a977ae3ce9b6b20524f7e0/scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala#L210-L220),

Adding the following options might help you :)

```
runner.optimizer.escapeInPathologicalCases (default false)
runner.optimizer.maxVisitsPerToken (default 513)
```

Though changing those options can cause slow formatting(better than just error...), we might want to add some error message to change those options for avoiding SearchStateExploded 🤔

**Comment by poslegm** [comment]
As far as I know it can be made only by manual exception handling on `Scalafmt.format` calls for every file. There is no built-in configuration for warn producing.

**Comment by pauljamescleary** [comment]
thanks @tanishiking , I will tinker with those settings to see if that helps.  I still think it is valuable to be able to set a setting that warns instead of errors.  Like, walk every file and report out in `warn` errors but do not fail.  If this is in scalafmt that would be great
